# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build

on:
  push:
    branches: ["*"]

env:
  net_version: "9.0"

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.net_version}}.x
      - name: Restore dependencies
        run: dotnet restore ./BlinkLab.sln
      - name: Build editor
        run: dotnet build --no-restore -c Release -o ./bin/editor ./src/Editor/BlinkLab.Editor.csproj
      - name: Build runtime
        run: dotnet build --no-restore -c Release -o ./bin/runtime ./src/Runtime/BlinkLab.Runtime.csproj
      - name: Upload editor binary
        uses: actions/upload-artifact@v4.5.0
        with:
          name: ${{ matrix.os }}-editor
          path: ./bin/editor
      - name: Upload runtime binary
        uses: actions/upload-artifact@v4.5.0
        with:
          name: ${{ matrix.os }}-runtime
          path: ./bin/runtime
