# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Check

on:
  pull_request:
    branches: ["*"]

env:
  net_version: "9.0"

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        config: [Release, Debug]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.net_version }}.x
      - name: Restore dependencies
        run: dotnet restore ./BlinkLab.sln
      - name: Build editor
        run: dotnet build --no-restore --verbosity diag -c ${{ matrix.config }} -o ./bin/editor ./src/Editor/BlinkLab.Editor.csproj
      - name: Build runtime
        run: dotnet build --no-restore --verbosity diag -c ${{ matrix.config }} -o ./bin/runtime ./src/Runtime/BlinkLab.Runtime.csproj
      - name: Check for NOTICES.txt (unix)
        if: ${{ runner.os != 'Windows' }}
        run: |
          test -f ./bin/editor/NOTICES.txt
          test -f ./bin/runtime/NOTICES.txt
      - name: Check for NOTICES.txt (windows)
        if: ${{ runner.os == 'Windows' }}
        run: |
          Test-Path ./bin/editor/NOTICES.txt
          Test-Path ./bin/runtime/NOTICES.txt
      - name: Upload editor binary
        uses: actions/upload-artifact@v4.5.0
        with:
          name: ${{ github.event.pull_request.title }}_${{ matrix.os }}(${{ matrix.config }})-editor
          path: ./bin/editor
      - name: Upload runtime binary
        uses: actions/upload-artifact@v4.5.0
        with:
          name: ${{ github.event.pull_request.title }}_${{ matrix.os }}(${{ matrix.config }})-runtime
          path: ./bin/runtime

